include:
  - board: eyelash_nano
    shield: offsetkey_left nice_oled
    snippet: studio-rpc-usb-uart
  - board: eyelash_nano
    shield: offsetkey_right nice_oled
  - board: eyelash_nano
    shield: settings_reset