include:
  - board: eyelash_nano
    shield: offsetkey_left nice_oled
  - board: eyelash_nano
    shield: offsetkey_right nice_oled
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
  - board: eyelash_nano
    shield: settings_reset