# === 左手配置，仅在左手生效 ===

# 启用输入，官方文档没有这条，不知道是哪个依赖需要的
CONFIG_INPUT=y
# 启用额外供电，如RGB，OLED屏幕等
CONFIG_ZMK_EXT_POWER=y

# === PMW3610轨迹球传感器相关 ===
CONFIG_PMW3610=y
# 不交换xy轴坐标
CONFIG_PMW3610_SWAP_XY=n
# x轴坐标翻转
CONFIG_PMW3610_INVERT_X=y
# y轴坐标不翻转
CONFIG_PMW3610_INVERT_Y=n
# 最小上报采样间隔，单位ms，数值越小延迟越低，但耗电增加；数值越大光标越卡顿
CONFIG_PMW3610_REPORT_INTERVAL_MIN=12
# 上电初始化额外等待 200ms，保证传感器稳定启动，避免读取异常
CONFIG_PMW3610_INIT_POWER_UP_EXTRA_DELAY_MS=200

# === Studio (Central only) ===
CONFIG_ZMK_STUDIO=y
# 开启蓝牙管理
CONFIG_ZMK_BLE_MANAGEMENT=y
CONFIG_ZMK_BLE_MANAGEMENT_STUDIO_RPC=y

# === Runtime Input Processor (Central only) ===
CONFIG_ZMK_RUNTIME_INPUT_PROCESSOR=y
CONFIG_ZMK_RUNTIME_INPUT_PROCESSOR_STUDIO_RPC=y

# === Settings RPC (Central only) ===
CONFIG_ZMK_SETTINGS_RPC=y
CONFIG_ZMK_SETTINGS_RPC_STUDIO=y

# === Runtime Sensor Rotate (Encoder, Central only) ===
CONFIG_ZMK_RUNTIME_SENSOR_ROTATE=y
CONFIG_ZMK_RUNTIME_SENSOR_ROTATE_STUDIO_RPC=y

# === Settings (Central only) ===
CONFIG_SETTINGS=y

# === Battery (Central only) ===
CONFIG_ZMK_BATTERY_HISTORY=n
CONFIG_ZMK_BATTERY_HISTORY_STUDIO_RPC=n

# === Split (Central only) ===
CONFIG_ZMK_SPLIT_RELAY_EVENT=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_SPLIT_RUN_STACK_SIZE=1024
CONFIG_ZMK_SETTINGS_SAVE_DEBOUNCE=10000
